### ISSUE TITLE
Plots for Tutorial 3 not present

### ISSUE THREAD

**Issue by nahorp** [ABindoff/R_tutorials#1]
Tutorials 1 and 2 show the graphs and plots correctly. However, Tutorial 3 does not show the graphs and only a blank space in seen. The .Rmd and .MD file look fine in RStudio and another Markdown reader but for some reason it is not rendering on Github (see screenshot below).

<img width="906" alt="Screen Shot 2020-03-23 at 7 00 07 pm" src="https://user-images.githubusercontent.com/43395036/77294728-e07b6200-6d38-11ea-9a40-7967d2f2fb9b.png">

**Comment by ABindoff** [comment]
Hi nahorp, github doesn't render the LaTeX correctly, but I recommend cloning the repo and running the code in R Studio anyway - much better learning experience overall.
